import { Formation, Position } from '../entities';

export const FORMATION_PRESETS: Formation[] = [
  {
    id: '4-4-2',
    name: '4-4-2 Classic',
    positions: [
      { id: 'gk', x: 50, y: 88, label: 'GK' },
      { id: 'rb', x: 15, y: 75, label: 'RB' },
      { id: 'cb-1', x: 35, y: 75, label: 'CB' },
      { id: 'cb-2', x: 65, y: 75, label: 'CB' },
      { id: 'lb', x: 85, y: 75, label: 'LB' },
      { id: 'rm', x: 15, y: 50, label: 'RM' },
      { id: 'cm-1', x: 35, y: 50, label: 'CM' },
      { id: 'cm-2', x: 65, y: 50, label: 'CM' },
      { id: 'lm', x: 85, y: 50, label: 'LM' },
      { id: 'st-1', x: 35, y: 20, label: 'ST' },
      { id: 'st-2', x: 65, y: 20, label: 'ST' },
    ],
  },
  {
    id: '4-3-3',
    name: '4-3-3 Attacking',
    positions: [
      { id: 'gk', x: 50, y: 88, label: 'GK' },
      { id: 'rb', x: 15, y: 75, label: 'RB' },
      { id: 'cb-1', x: 35, y: 75, label: 'CB' },
      { id: 'cb-2', x: 65, y: 75, label: 'CB' },
      { id: 'lb', x: 85, y: 75, label: 'LB' },
      { id: 'cdm', x: 50, y: 60, label: 'CDM' },
      { id: 'cm-1', x: 30, y: 45, label: 'CM' },
      { id: 'cm-2', x: 70, y: 45, label: 'CM' },
      { id: 'rw', x: 15, y: 25, label: 'RW' },
      { id: 'st', x: 50, y: 15, label: 'ST' },
      { id: 'lw', x: 85, y: 25, label: 'LW' },
    ],
  },
  {
    id: '3-5-2',
    name: '3-5-2 Balanced',
    positions: [
      { id: 'gk', x: 50, y: 88, label: 'GK' },
      { id: 'cb-1', x: 25, y: 75, label: 'CB' },
      { id: 'cb-2', x: 50, y: 75, label: 'CB' },
      { id: 'cb-3', x: 75, y: 75, label: 'CB' },
      { id: 'rm', x: 10, y: 55, label: 'RM' },
      { id: 'cm-1', x: 30, y: 55, label: 'CM' },
      { id: 'cam', x: 50, y: 40, label: 'CAM' },
      { id: 'cm-2', x: 70, y: 55, label: 'CM' },
      { id: 'lm', x: 90, y: 55, label: 'LM' },
      { id: 'st-1', x: 35, y: 20, label: 'ST' },
      { id: 'st-2', x: 65, y: 20, label: 'ST' },
    ],
  },
  {
    id: '5-3-2',
    name: '5-3-2 Defensive',
    positions: [
      { id: 'gk', x: 50, y: 88, label: 'GK' },
      { id: 'rb', x: 10, y: 75, label: 'RB' },
      { id: 'cb-1', x: 30, y: 75, label: 'CB' },
      { id: 'cb-2', x: 50, y: 75, label: 'CB' },
      { id: 'cb-3', x: 70, y: 75, label: 'CB' },
      { id: 'lb', x: 90, y: 75, label: 'LB' },
      { id: 'cm-1', x: 30, y: 50, label: 'CM' },
      { id: 'cm-2', x: 50, y: 50, label: 'CM' },
      { id: 'cm-3', x: 70, y: 50, label: 'CM' },
      { id: 'st-1', x: 35, y: 20, label: 'ST' },
      { id: 'st-2', x: 65, y: 20, label: 'ST' },
    ],
  },
  {
    id: '4-2-3-1',
    name: '4-2-3-1 Modern',
    positions: [
      { id: 'gk', x: 50, y: 88, label: 'GK' },
      { id: 'rb', x: 15, y: 75, label: 'RB' },
      { id: 'cb-1', x: 35, y: 75, label: 'CB' },
      { id: 'cb-2', x: 65, y: 75, label: 'CB' },
      { id: 'lb', x: 85, y: 75, label: 'LB' },
      { id: 'cdm-1', x: 35, y: 60, label: 'CDM' },
      { id: 'cdm-2', x: 65, y: 60, label: 'CDM' },
      { id: 'cam', x: 50, y: 40, label: 'CAM' },
      { id: 'rw', x: 20, y: 30, label: 'RW' },
      { id: 'lw', x: 80, y: 30, label: 'LW' },
      { id: 'st', x: 50, y: 15, label: 'ST' },
    ],
  },
];

export const CUSTOM_FORMATION: Formation = {
  id: 'custom',
  name: 'Custom Formation',
  positions: [],
};